CREATE TABLE prices (
    ID BIGINT PRIMARY KEY,
    ID_PRODUCT BIGINT NOT NULL,
    ID_BRAND BIGINT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    ID_PRICE_LIST BIGINT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    ID_CURRENCY_TYPE BIGINT NOT NULL
);